circles/circles/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("authentication/", include("authentication.urls"))
]

circles/main/urls.py
from django.urls import path

from . import views

app_name = "main"
urlpatterns = [
    path("", views.index, name="index"),
    path("main/", views.main, name="main"),
    path("privacy/", views.privacypolicy, name="privacypolicy"),
    path("test/", views.test, name="test")
]

circles/main/models.py
from django.db import models
from django.utils import timezone
from authentication.models import User
from django.core.exceptions import ValidationError

class Server(models.Model):
    name = models.CharField(max_length=256)
    ip = models.CharField(max_length=256)
    admins = models.ManyToManyField(User, blank=True)
    production = models.BooleanField(default=1)
    account_creation = models.BooleanField(default=1)
    websocket_accept = models.BooleanField(default=1)

    def __str__(self):
        return(self.name)
    
    class Meta:
        verbose_name_plural = "Server"


class Circle(models.Model): # Any circle within the server. Circles can also be inside a Circle
    name = models.CharField(max_length=256, default="no-name")
    parent_circle = models.ForeignKey("self", on_delete=models.CASCADE, blank=True, null=True)
    parent_server = models.ForeignKey(Server, on_delete=models.SET_NULL, blank=True, null=True)
    x = models.IntegerField(default=0)
    y = models.IntegerField(default=0)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name="circle_creator")

    def __str__(self):
        if self.parent_circle:
            string = self.parent_circle or ""
            return(f"{string} / {self.name}")
        
        elif self.parent_server:
            string = self.parent_server or ""
            return(f"{string} / {self.name}")
        
        else:
            return(f"/!\ --- {self.name}")

class Conversation(models.Model): # A private conversation between users. Has a list of the users in it
    name = models.CharField(max_length=256, default="no-name")
    date_time_created = models.DateTimeField(default=timezone.now)
    users = models.ManyToManyField(User, blank=True)
    creator = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL, related_name="conversation_creator")
    

    def __str__(self):
        if self.users.count() == 1:
            return(f"'{self.name}' with {self.users.count()} person")
        
        else:
            return(f"'{self.name}' with {self.users.count()} people")
        

class Message(models.Model): # A message from a user. Has date, time, username and Conversation / Circle information (Message can belong to a specific Circle or a specific Conversation)
    text = models.CharField(max_length=2000, default="Empty Message")
    date_time_created = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE, blank=True, null=True)
    circle = models.ForeignKey(Circle, on_delete=models.SET_NULL, blank=True, null=True)
    current_conversation_type = models.CharField(max_length=16, default="normal")

    def __str__(self):
        if len(self.text) > 75:
            return(f"[{self.user.username}] {self.text[:75]}...")
        
        else:
            return(f"[{self.user.username}] {self.text[:75]}")
        
    def clean(self, *args, **kwargs):
        if self.conversation and self.circle:
            raise ValidationError("Message should be in a Conversation or a Circle, but not both.")
        
        if not self.user:
            raise ValidationError("A user is required.")
        
        return super().clean()

circles/main/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.staticfiles import finders
from authentication.views import sign_in
from main.models import Server
import os

def index(request):
    commit_hash = os.popen("git rev-parse --short HEAD").read()
    server_info = Server.objects.all()[0]
    
    context = {
        "server_name": server_info.name,
        "server_ip": server_info.ip,
        "production": server_info.production,
        "commit": commit_hash
    }

    try:
        username_session = request.session["username"]
        password_session = request.session["password"]

        return sign_in(request)

    except KeyError:
        context = {
            "server_name": server_info.name,
            "server_ip": server_info.ip,
            "production": server_info.production,
            "commit": commit_hash
        }
        print("No session!")
        return render(request, "index.html", context)
    
def main(request):
    commit_hash = os.popen("git rev-parse --short HEAD").read()

    server_info = Server.objects.all()[0]

    try:
        username_session = request.session["username"]
        password_session = request.session["password"]

        context = {
            "username": username_session,
            "server_name": server_info.name,
            "server_ip": server_info.ip,
            "production": server_info.production,
            "commit": commit_hash
        }

        return render(request, "main.html", context)
    
    except KeyError:
        context = {
            "server_name" : server_info.name,
            "server_ip": server_info.ip,
            "production": server_info.production,
            "commit": commit_hash
        }
        print("No session!")
        return render(request, "index.html", context)
    
def privacypolicy(request):
    return render(request, "privacypolicy.html")

def test(request):
    return render(request, "test.html")

circles/main/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Circles</title>
        <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'main/ui.css' %}">
        <link rel="icon" type="image/x-icon" href="{% static 'main/images/favicon.ico' %}">
        <script src="https://unpkg.com/@phosphor-icons/web"></script>
        <meta name="darkreader-lock">
    </head>

    <body>
        <div class="blob" id="blob1"></div>
        <div class="blob" id="blob2"></div>
        <div class="blob" id="blob3"></div>
        <div class="blob" id="blob4"></div>

        <div id="particles-js"></div>

        <div id="nav-bar">
            <img id="nav-logo" src="{% static 'main/images/circles.png' %}" class="fade_in_scale">
            <div class="nav-spacer"></div>
        </div>


        <div id="main-main">
            <div id="main-box">
                <p id="main-header-text" class="text-medium fade_in_scale">Welcome to</p>
                <img id="main-header_image" src="{% static 'main/images/circles.png' %}" class="fade_in_scale">
                <p id="main-header-subtext" class="text-small fade_in_scale">Find your Circle</p>
                <div id="main-header_line" class="fade_in_scale"></div>
                <div id="main-header-buttonbox">
                    <button class="button fade_in_scale" id="button_signup">Sign Up</button>
                    <button class="button fade_in_scale" id="button_login">Log In</button>
                </div>
            </div>

            <div id="auth-box">
                <div id="auth-box-text">
                    <div id="auth-box-text-column">
                        <p id="auth-box-text-label" class="dialog-header">Join Circles</p>
                        <p id="auth-box-text-server" class="dialog-subheader">Creating an account at circles.media</p> <!-- Connect to django to display server name -->
                    </div>
                    <p id="auth-box-close" class="buttonx">X</p>
                </div>

                <div id="auth-box-login" class="fade_in">
                    <br>
                    <div class="criticalbox fade_in" id="auth-box-login-warning">
                        <p id="auth-box-login-warning-text">warning message</p>
                    </div>
                    <br>

                    <div id="auth-box-textarea">
                        <input class="textarea" placeholder="Username" type="text" id="auth-box-textarea-login-username"></input>
                        <p class="textedit-subtext">This is the shorter username you created your account with.</p>
                    </div>

                    <div id="auth-box-textarea">
                        <input class="textarea" placeholder="Password" type="password" id="auth-box-textarea-login-password"></input>
                    </div>

                    <div id="auth-box-buttonbox-onebutton">
                        <button class="buttonsmaller" id="auth-box-buttonbox-login">Log In</button>
                    </div>

                </div>

                <div id="auth-box-username" class="fade_in">
                    <br>

                    <div class="infobox">Hi! Circles is very experimental right now. Bugs are to be expected. Please report issues <a href="https://github.com/nfoert/circles/issues">here</a></div>
                    <div id="auth-box-textarea">
                        <input class="textarea" placeholder="Username" type="text" id="auth-box-textarea-username-username"></input>
                        <p class="textedit-subtext">Create a short, memorable and unique username. This is how people can find you. You can't change this later.</p>
                    </div>

                    <div id="auth-box-buttonbox-onebutton">
                        <button class="buttonsmaller" id="auth-box-buttonbox-next-username">Next</button>
                    </div>
                    

                </div>
                
                <div id="auth-box-email" class="fade_in">
                    <br>

                    <div id="auth-box-textarea">
                        <input class="textarea" placeholder="Email" type="text" id="auth-box-textarea-email-email"></input>
                        <p class="textedit-subtext">Your email will be used to verify the account and to send security information.</p>
                    </div>

                    <div id="auth-box-buttonbox">
                        <button class="buttonsmaller" id="auth-box-buttonbox-back-email">Back</button>
                        <button class="buttonsmaller" id="auth-box-buttonbox-next-email">Next</button>
                    </div>

                </div>
                <div id="auth-box-password" class="fade_in">

                    <div id="auth-box-textarea">
                        {% csrf_token %}
                        <input class="textarea" placeholder="Password" type="password" id="auth-box-textarea-password-password"></input>
                        <input class="textarea" placeholder="Confirm Password" type="password" id="auth-box-textarea-password-confirmpassword" style="margin-top:10px"></input>
                    </div>

                    <div id="auth-box-password-validate">
                        <div class="auth-box-password-validate-segment" id="auth-box-password-validate-1"></div>
                        <div class="auth-box-password-validate-segment" id="auth-box-password-validate-2"></div>
                        <div class="auth-box-password-validate-segment" id="auth-box-password-validate-3"></div>
                        <div class="auth-box-password-validate-segment" id="auth-box-password-validate-4"></div>
                    </div>

                    <p class="textedit-subtext" id="auth-box-password-strength">No Password</p>
                    <p class="textedit-subtext">Strong passwords contain 8 or more characters, a symbol, a number and a capital letter.</p>

                    <div id="auth-box-buttonbox">
                        <button class="buttonsmaller" id="auth-box-buttonbox-back-password">Back</button>
                        <button class="buttonsmaller" id="auth-box-buttonbox-next-password">Next</button>
                    </div>

                    
                </div>

                <div id="auth-box-rules" class="fade_in">

                    <div class="criticalbox fade_in" style="display: none;" id="createaccount_warning_box">warning message</div>

                    <p class="text-small">Server Rules</p>

                    <p class="textedit-subtext"><i class="ph-bold ph-heart-break"></i> No racism, sexism, bullying, homophobia or other hate based messages</p>
                    <p class="textedit-subtext"><i class="ph-bold ph-hands-praying"></i> No politics or religion unless in specific Circles designed for such discussion</p>
                    <p class="textedit-subtext"><i class="ph-bold ph-user"></i> Be kind and respect people</p>
                    <p class="textedit-subtext"><i class="ph-bold ph-mask-sad"></i> Do not threaten or harass other members of the Server</p>
                    <p class="textedit-subtext"><i class="ph-bold ph-credit-card"></i> Don't share personal information</p>
                    <p class="textedit-subtext"><i class="ph-bold ph-chats-teardrop"></i> Don't spam</p>
                    <p class="textedit-subtext"><i class="ph-bold ph-globe-hemisphere-west"></i> Please use English unless in Circles designed for other languages</p>
                    <p class="textedit-subtext"><i class="ph-bold ph-x-circle"></i> No NSFW or illegal content</p>

                    <br>
                    <p class="textedit-subtext"><i class="ph-bold ph-gavel"></i> Violating these rules will result in a suspension or ban</p>
                    <p class="textedit-subtext"><strong><a href="{% url 'main:privacypolicy' %}" style="text-decoration: none; color: white;"><i class="ph-bold ph-lock-simple"></i> Privacy Policy</a></strong></p>

                    <div id="auth-box-buttonbox">
                        <button class="buttonsmaller" id="auth-box-buttonbox-back-rules">Back</button>
                        <button class="buttonsmaller" id="auth-box-buttonbox-createaccount-rules">Create Account</button>
                    </div>
                </div>
            </div>

            
            
            <div id="background-darkness"></div>

            


        </div>


        <div id="commit-hash"><a href="https://github.com/nfoert/circles/commit/{{ commit }}">Commit {{ commit }}</a></div>

        <script>
            var server_name = "{{ server_name }}"
            var server_ip = "{{ server_ip }}"
            var production = "{{ server_ip }}"
        </script>

        <script src="{% static 'main/scripts/authbox.js' %}"></script>
        <script src="{% static 'main/scripts/particles.js' %}"></script>
        <script src="{% static 'main/scripts/index.js' %}"></script>
    </body>
</html>

circles/main/templates/privacypolicy.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Circles | Privacy Policy</title>
        <link rel="stylesheet" type="text/css" href="{% static 'main/privacypolicy.css' %}">
        <link rel="icon" type="image/x-icon" href="{% static 'main/images/favicon.ico' %}">
        <meta name="darkreader-lock">
        <script src="https://unpkg.com/@phosphor-icons/web"></script>
    </head>

    <body>
        <img id="background-image" src="{% static 'main/images/bg.png' %}">

        <div id="top-box">
            <img class="animate" src="{% static 'main/images/icon.png' %}">
            <h1 class="animate">Privacy Policy</h1>
        </div>
        
        <hr class="animate" align="left">

        <div id="content" class="animate">
            <p>Most documents like this is a mess of legal terms that the normal person doesn't have the time or patience to read. Here, I'm clearly describing what data is collected, how it's stored and what we do with it. In plain English. Nothing else.</p>
            
            <h2 id="what-data-is-collected"><i class="ph-bold ph-pencil-simple"></i> What data is collected?</h2>
            <p>Below I've created categories for each kind of item in Circles. From a User account to a Message, this is what data is assigned to each item.</p>
            
            <h3 id="user"><i class="ph-bold ph-user"></i> User</h3>
            <ul>
                <li>Username</li>
                <li>Password (Hashed)</li>
                <li>Email</li>
                <li>Display Name</li>
                <li>Profile bio</li>
                <li>Primary color for your profile preview and appearence</li>
                <li>Secondary color for your profile preview and appearence</li>
                <li>Current x and y position</li>
                <li>Online status</li>
                <li>Settings</li>
                <li>Statistics</li>
                <li><strong>Server</strong> and <strong>Circle</strong> location</li>
                <li>Selected <strong>Conversation</strong> and <strong>Conversation</strong> type</li>
                <li>Followers</li>
                <li>Account Created date</li>
            </ul>

            <h3 id="circle"><i class="ph-bold ph-circle"></i> Circle</h3>
            <ul>
                <li>Name of <strong>Circle</strong></li>
                <li>Parent <strong>Circle</strong> or <strong>Server</strong></li>
                <li>x and y position</li>
                <li>The <strong>User</strong> that created the <strong>Circle</strong></li>
            </ul>

            <h3 id="conversation"><i class="ph-bold ph-chat-teardrop-text"></i> Conversation</h3>
            <ul>
                <li>The name of the <strong>Conversation</strong></li>
                <li>The date and time when the <strong>Conversation</strong> was created</li>
                <li>The <strong>Users</strong> in the <strong>Conversation</strong></li>
            </ul>

            <h3 id="message"><i class="ph-bold ph-chat-text"></i> Message</h3>
            <ul>
                <li>The contents of the <strong>Message</strong></li>
                <li>The date and time when the <strong>Message</strong> was created</li>
                <li>The <strong>User</strong> that created the <strong>Message</strong></li>
                <li>The <strong>Conversation</strong> or <strong>Circle</strong> that the <strong>Message</strong> is in</li>
                <li>The current type of the <strong>Message</strong></li>
            </ul>

            <h3 id="statistics"><i class="ph-bold ph-chart-bar"></i> Statistics</h3>
            <p>Some simple statistics are tracked. Mainly used for fun reasons than anything else. Eventually, you'll get badges for doing certain things. Tracking can be opted out in the settings page.</p>
            <ul>
                <li>Times logged in</li>
                <li>Number of <strong>Messages</strong> sent</li>
                <li>Distance moved (in three.js units)</li>
                <li>Number of <strong>Conversations</strong> created</li>
                <li>Times switched to a different <strong>Converstaion</strong></li>
                <li>Times switched to a different <strong>Circle</strong></li>
            </ul>

            <h2 id="what-data-is-shared-with-others"><i class="ph-bold ph-share-network"></i> What data is shared with others?</h2>
            <p>Right now, there aren't any other services that use any of your data. In future, when the ability to connect your Circles account with other services and servers becomes available, this section will be updated.</p>
            
            <h2 id="what-data-is-sold-to-others"><i class="ph-bold ph-money"></i> What data is sold to others?</h3>
            <p>Nothing. Ever. If you're worried you could self host once the necessary infrastructure is finished.</p>
            
            <p><em>Last updated 11/16/23</em></p>
        </div>

        
        
        <div id="footer">
            <hr class="animate" align="left">

            <p id="footer-main">Circles</p>

            <a class="footer-link" href="https://github.com/nfoert/circles"><i class="ph-bold ph-github-logo"></i> Source Code</a>
            <a class="footer-link" href="https://github.com/nfoert/circles/issues"><i class="ph-bold ph-bug-beetle"></i> Report an Issue</a>
            <a class="footer-link" href="https://discord.com/invite/QBDw4UrGXX"><i class="ph-bold ph-discord-logo"></i> Discord</a>

            <hr class="animate" align="left">
        </div>

        
    </body>
</html>

circles/main/templates/test.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <title>Circles | Test</title>
        <link rel="stylesheet" type="text/css" href="{% static 'main/ui.css' %}">
        <link rel="icon" type="image/x-icon" href="{% static 'main/images/favicon.ico' %}">

        <script src="https://unpkg.com/@phosphor-icons/web"></script>
        <script type="module" src="https://cdn.jsdelivr.net/npm/emoji-picker-element@^1/index.js"></script>
    </head>

    <body style="background-color: #35363E;">
        <p class="text-medium">text-medium</p>
        <p class="text-small">text-small</p>
        <p class="text-small-left">text-small-left</p>
        <p class="text-tiny">text-tiny</p>

        <hr>

        <p class="dialog-header">dialog-header</p>
        <p class="dialog-subheader">dialog-subheader</p>

        <hr>

        <p class="textedit-subtext">textedit-subtext</p>
        <p class="user-in-conversation">user-in-conversation</p>

        <hr>

        <button class="button">button</button>
        <button class="buttonsmaller">buttonsmaller</button>
        <button class="buttontiny">buttontiny</button>
        <p class="buttonx">X</p>
        <button class="buttonsmallcircle"><i class="ph-bold ph-circle"></i></button>
        <button class="mention">@jadesoftware</button>
        <button class="mention-you">@nfoert</button>
        <div class="rectangle-button">rectangle-button</div>

        <hr>

        <input type="text" class="textarea" placeholder="textarea">
        <input type="color" class="textarea-color" placeholder="textarea-color">

        <hr>

        <div class="infobox">infobox</div>
        <div class="criticalbox">criticalbox</div>
        <div class="warningbox">warningbox</div>

        <hr>

        <div class="checkbox-layout">
            <div class="checkbox"><input type="checkbox" class="setting" default="true" setting="stat_tracking"></div>
            <p class="checkbox-text">Checkbox</p>
        </div>

        <hr>

        <div class="line"></div>
        
        <hr>

        <div class="reaction">1 😭</div>
        <div class="reaction">5 ❤️</div>
        <div class="reaction">3 🤣</div>

        <hr>

        <emoji-picker></emoji-picker>


    </body>

</html>